RVC-Boss/GPT-SoVITS

README.md

Ubuntu 22.04 LTS
reported: 
>>> OSError: libsox.so: cannot open shared object file: No such file or directory
>>> RuntimeError: Error in dlopen: libavutil.so.58: cannot open shared object file: No such file or directory
>>> DEBUG:torchaudio._extension.utils:Attempting to load FFmpeg version 6, 5, 4. not found

Update README.md for Ubuntu

---

requirements.txt

Line 27 of webui.py contains an import from i18n.i18n but there was no module in the requirements.
I added the module i18n.
Line for context: "from i18n.i18n import I18nAuto"

Fixed i18n error

---

GPT_SoVITS/utils.py

When using `inference_webui.py`, it produces debug level info for http requests, for example: 
```
DEBUG:httpcore.http11:response_closed.started
```
Here I changed it to warning level.

Disable debug level logging

---

tools/uvr5/webui.py

如题，有用户称在读取音频的metadata时出现问题，这可能是ffprobe造成的。
部分站点在存在写入不合规metadata的情况（如一些直播站点将直播间信息写入metadata，其中包含emoji等乱七八糟信息，可能这些站点之前前端不支持这些信息，后续支持后并没有对流媒体方面对接这些功能），这在ffmpeg.probe时将会出现问题。 
考虑到ffmpeg兼容性和性能比librosa更好，可能在导入前对metadata合规性处理会更好？ 
但是看到后面注释部分很多地方还是使用librosa实现，所以暂且认为还不用考虑兼容性问题。

使用librosa加载音频避免ffmpeg.probe读取metadata的错误

---

api.py

While I'm testing on both my GTX 1060 platform and E5-2678 v3 server, I noticed such a sort of error message. Since MPS device is only for Apple platforms, this method shouldn't be invoked if api server is running on other platforms. Besides, I have no experience with Artificial Intelligence development and I'm just a junior high school student in China Mainland, so if there's any issue with this pr, please edit the code by yourselves. : -)
```
INFO:     1.1.1.1:0 - "GET /?text=Hey+there!&text_language=en HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
File "F:\GPT-SoVITS-beta0128\runtime\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 407, in run_asgi
result = await app(  # type: ignore[func-returns-value]
File …
```

Fix "AttributeError: module 'torch' has no attribute 'mps'" in api.py while running on non-Apple platform

---

.gitignore
Docker/download.py

1. 调整Dockerfile所使用模型下载脚本，使得和cmd-asr.py版本保持一致
2. gitignore里增加几个内容输出目录

调整Dockerfile所使用模型下载脚本

---

tools/uvr5/lib/lib_v5/spec_utils.py
tools/uvr5/vr.py

Librosa 更新到 0.10.0+ 时，位置参数需要修改为关键字参数，且不影响 Libsora=0.9.2 时运行。
否则会出现
```
TypeError: load() takes 1 positional argument but 3 positional arguments (and 2 keyword-only arguments) were given
```

适配更高版本的 librosa

---

GPT_SoVITS/inference_webui.py

test case:
```
def replace1(text):
return text.replace("\n\n", "\n").replace("\n\n", "\n").replace("\n\n", "\n")
def replace2(text):
while "\n\n" in text:
text = text.replace("\n\n", "\n")
return text
text = "123456789\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n987654321"
print(replace1(text))
print("--------------")
print(replace2(text))
```

feat: incase too much \n

---

GPT_SoVITS/inference_webui.py

有时，字太少时，合成会被忽略掉
如图，输出结果中，
"近日"和"对此" 会被忽略（在输出结果中就没有对应的音频）
get_tts_wav函数入参：
```
ref_wav_path = 上传结果
prompt_text = 上传结果
prompt_language = "Chinese"
text = "近日，茶饮品牌茶颜悦色工商变更，企业类型变更并引入新股东，市场猜测是为赴港上市做准备。对此，茶颜悦色方面对此回应称，暂时没有明确的上市计划。对于茶颜悦色的这系列变更，一家关注消费行业的投资机构分析师表示，股权变更可能是在为上市做准备，但并不代表最后能上市，是上市的必要不充分条件。但是股权变更也可能是其他情况，比如架构重组，开展新业务，引入新股东。（红星新闻）。"
text_language = "Chinese"
how_to_cut = "按标点符号切"
```
merge_short_text_in_array 函数测试
```
def merge_short_text_in_array(texts, threshold):
if (len(texts)) < 2:
return texts
result = []
text = ""
for ele in texts:
text += ele
if len(text) >= threshold:
result.append(text)
text = ""
if (len(text) > 0):
if len(result) == 0:
result.append(text)
else:
result[len(result) - 1] += text
return result
texts = []
text = ""
for i in range(1, 10):
text = text + str(i) …
```

feat: in case ignore too short text

---

.dockerignore
Dockerfile
dockerbuild.sh

优化Docker分层，尽可能复用缓存；
增加条件构建，可以用IMAGE_TYPE参数构建不包含额外模型的Docker镜像来减少镜像大小；
增加批量构建Docker镜像脚本

优化Dockerfile --- 新年快乐

---

GPT_SoVITS/inference_webui.py

在clean_text_inf引入LangSegment.getTexts进行处理，解决：
1、选择全英文、全中文、全日文，但实际输入文本非纯语种，此时全日文会开始口胡的问题。
2、全英文、中英混合、日英混合对纯大写英文输入没有进行优化处理，仍会口胡朗读。

Adjust-tts-clean-text

---

.gitignore
GPT_SoVITS/AR/models/t2s_model.py
GPT_SoVITS/AR/models/utils.py
GPT_SoVITS/inference_webui.py

1. 为训练部分添加的DPO协同训练，相关修改见：
GPT_SoVITS\AR\models\t2s_model.py
GPT_SoVITS\AR\models\utils.py
这两个文件，修改后的模型已经在最新的代码上测试完毕。
DPO注意事项：
DPO会将训练显存翻倍，建议batch_size减半，可在文档中添加相关说明。
2. 生成部分添加：top_k, top_p, temperature的控制，可以方便控制稳定的输出(降低这些参数)，如图：
以上功能均已测试通过
**DPO特性说明：**DPO为一种偏好对齐算法，可以有效缓解生成时模型所具有的幻觉，输出不友好等问题，为该项目添加该功能的目的在于缓解生成的文本内容丢失，优化克隆人物的语气。
**生成参数说明：**将部分采样参数暴露到webui界面，方便生成时调整，可以通过降低温度，降低top_p,top_k 提升模型输出内容的一致性。

添加DPO协同训练，提升输出内容的稳定性，增加部分生成参数的webui控制

---

GPT_SoVITS/inference_webui.py

因日文汉字与中文汉字存在相同字符问题，修改目标语种为日文/日英时，不丢弃识别的中文的字符，以用户输入文字为准。
在混合语种模式下，仍会出现日文汉字当中文汉字的问题，处理方法参照LangSegment文档打标处理。
```
text = "你的名字叫<ja>佐々木？<ja>"  
text = "你的名字叫<ja>佐々木？</ja>"  
```

Adjust ja clean text

---

GPT_SoVITS/text/english.py

热词应该是覆盖逻辑，因为原版字典里如果key存在的话，那么用户定义的热词纠正发音就不会生效，举个例子，原版字典里AI这个key的发音是AH0，但实际上应该是EY1 - AY1，但如果用户在热词字典了定义了新的读音EY1 - AY1，是不生效的，以为原版字典里已经有了AI的key，所以理论上热词字典新定义的key应该是覆盖原字典key的逻辑

修正g2p_en的英文字母发音问题

---

colab_webui.ipynb

Modified the way we retrieve the "is_share" environment variable.

Fix Issue with Share Link Generation in colab_webui.ipynb

---

GPT_SoVITS/inference_webui.py
config.py

Using CPU inference on Mac to accelerate inference speed and reduce memory leak

Change the inference device on Mac

---

.dockerignore
dockerbuild.sh

1. Docker镜像构建脚本中增加Git Commit Hash值Tag
2. .dockerignore中增加排除的文件夹

Docker镜像构建脚本对于镜像的Tag增加Git Commit的Hash值，便于知道镜像中应用版本

---

tools/uvr5/mdxnet.py

使用onnx_dereverb模型去混响的输出文件夹是相反的，人声文件出现在了非人声文件夹，非人声文件出现在人声文件夹

fix MDX-Net output path

---

tools/uvr5/uvr5_weights/.gitignore
webui.py

I think if you want to import local module (e.g. `from toos import my_utils`) by modifying `sys.path`, it's better to replace `sys.path.apped()` with `sys.path.insert()`. Because some `tools` has been exists in `sys.path`.
```shell
File "/workspace/GPT-SoVITS/webui.py", line 44, in <module>
from tools import my_utils
ImportError: cannot import name 'my_utils' from 'tools' (/opt/conda/lib/python3.10/site-packages/tools/__init__.py)
```

bugfix for import local tools module failed

---

.gitignore
GPT_SoVITS/AR/models/t2s_model.py
GPT_SoVITS/AR/models/t2s_model_batch_only.py
GPT_SoVITS/AR/models/utils.py
GPT_SoVITS/TTS_infer_pack/TTS.py
GPT_SoVITS/TTS_infer_pack/TextPreprocessor.py
GPT_SoVITS/TTS_infer_pack/__init__.py
GPT_SoVITS/TTS_infer_pack/text_segmentation_method.py
GPT_SoVITS/configs/tts_infer.yaml
GPT_SoVITS/feature_extractor/cnhubert.py
GPT_SoVITS/inference_gui.py
GPT_SoVITS/inference_webui.py
GPT_SoVITS/inference_webui_old.py

- 重构优化了tts infer。在原有的基础上进行了逻辑功能拆分和优化。
- 批量推理支持。新增了T2S模型的批量推理支持，大幅改善了推理吞吐量，降低了推理时间。ps: vits还是串行推理。因为padding之后vits推理出来的音频会有问题。（可能会有方法可以mask掉？🤔）
- 与这项工作不同 #712 ，我对句子做了排序和分桶，并对T2S模型的批量推理做一定的计算优化。
测试环境：Windows 11, i5-13600KF + RTX4070
测试设置：fp16, batch_size=10 (Original 为1)，测试10次取均值
测试文本：
```
　　除却宝药外，小不点每日也在以符文为他治疗，半个月后，清风复原，其筋骨迅速愈合。
　　“宝药真厉害，拥有神效啊，这么快就好了。”众人啧啧称奇，却不知小不点所练的原始真解也起了极大的作用。
```
测试结果：
| Method | T2S (task/s) | VITS (task/s) |
| ---- | ---- | ---- | 
| Original | 0.207  | 0.702 |
| Batch inference | 0.706 | 0.857 |
| Batch inference + Torchscript w/o flash | 1.308 | 0.853 |
- 测试、更新中
Warning: 改动较大，建议大量测试后再merge。

tts infer重构优化和批量推理支持

---

GPT_SoVITS/AR/models/t2s_model.py

I rewrite the inference code for t2smodel.infer_panel, which can achieves about 1.2\~1.5 times faster inference speed. 
I tested the the token generation speed on a Windows PC and an Ubuntu server with a Geforce 3090 GPU. The token generation speed on Windows w/o `flash-attention` is up to 110\~120 tokens/s, and that on Ubuntu is up to170\~180 tokens/s. I think the main reason of generation speed difference is that SPDA in windows does not compiled with flash attention. By the way, the inference speed w/ flash attention on linux is about 220~230 tokens/s, and on Windows is about 140~150 tokens/s.
======Update 1=====
I change implementation with TorchScript, and backup the codes with flash attention in `flash-attn` branch.

T2S model inference optimization

---

GPT_SoVITS/AR/models/t2s_lightning_module.py
GPT_SoVITS/AR/models/t2s_model.py
GPT_SoVITS/TTS_infer_pack/TTS.py
GPT_SoVITS/TTS_infer_pack/TextPreprocessor.py
GPT_SoVITS/configs/tts_infer.yaml
GPT_SoVITS/inference_webui.py
tools/uvr5/uvr5_weights/.gitignore
webui.py

增加flash attention选项，防止影响训练

---

GPT_SoVITS/TTS_infer_pack/TTS.py
GPT_SoVITS/TTS_infer_pack/TextPreprocessor.py
GPT_SoVITS/TTS_infer_pack/text_segmentation_method.py
GPT_SoVITS/inference_webui.py
GPT_SoVITS/module/models.py

- 增加了VITS批量推理，进一步优化吞吐量，代码贡献自未知名的小伙伴。
- 修复了未继承主webui选项的模型的问题。
- 修复了大文本推理时，bert报错的问题。

新增VITS批量推理修复了一些bug

---

GPT_SoVITS/TTS_infer_pack/TTS.py
GPT_SoVITS/TTS_infer_pack/TextPreprocessor.py

测试语句: `本软件以MIT协议开源, 作者不对软件具备任何控制力, 使用软件者、传播软件导出的声音者自负全责.`
选择语言: `中英混合`/`多语种混合`
报错截图:
问题定位:
`TTS_infer_pack/TextPreprocessor.py` 中 `TextPreprocessor.extract_bert_feature()` 函数应该输出 `phones_list` 而不是 `phone`.
单语言时两者相同, 因此不出错; 多语言会产生多分段, 输出 `phone` 会只取最后一段, 和后续相关变量长度不对应.
- 将 `TTS_infer_pack/TTS.py/TTS_Config.__str__()` 打印固定配置项修改为遍历打印, 方便新增配置项.
- 打印结果进行对齐.
由
```
----------------TTS Config--------------
device: cuda
is_half: True
bert_base_path: GPT_SoVITS/pretrained_models/chinese-roberta-wwm-ext-large
t2s_weights_path: GPT_SoVITS/pretrained_models/s1bert25hz-2kh-longer-epoch=68e-step=50232.ckpt
vits_weights_path: GPT_SoVITS/pretrained_models/s2G488k.pth
cnhuhbert_base_path: GPT_SoVITS/pretrained_models/chinese-hubert-base
flash_attn_enabled: True
----------------------------------------
``` …

修复 Fast Inference 分支的多语言 bug

---

GPT_SoVITS/inference_webui.py
GPT_SoVITS/prepare_datasets/1-get-text.py
GPT_SoVITS/prepare_datasets/2-get-hubert-wav32k.py
GPT_SoVITS/prepare_datasets/3-get-semantic.py
GPT_SoVITS/s1_train.py
GPT_SoVITS/s2_train.py
README.md
api.py
docs/cn/README.md
docs/ja/README.md
docs/ko/README.md
webui.py

**In addition, according to #686, models trained with GPU on Macs result in lower quality, and I can also reproduce that.**
This is the CPU model:
https://github.com/RVC-Boss/GPT-SoVITS/assets/130235128/93e9103f-c8bf-42dc-9bf4-3d132f3364d5
And this is the mps model:
https://github.com/RVC-Boss/GPT-SoVITS/assets/130235128/86949193-50a9-413f-a67f-981abf0a994e
batch size: 16
CPU:
- So-VITS: about 8s/it
- GPT: about 0.6 it/s
mps:
- So-VITS: about 2s/it
- GPT: about 4it/s
So I advise to use CPU training on Macs.
Using CPU also "fixes" the memory leak issues, and now all Macs (or almost every computer) can do training.
We can add mps support once the problem is solved.
**I haven't tested it on other computers, but it should run on non-GPU devices.**

Support CPU training, use CPU on macOS

---

GPT_SoVITS/text/english.py

1. 将g2p_en的文字格式化内容前移至text_normalize，暴露至命令行使显示的文字与实际生成音素文字对应。
2. 重写g2p_en推理逻辑，将缩写A发音修正为"EY1"，量词a仍保持为"AH0"。同时减少递归重复运算。
3. 扩展所有格xxx's推理应有的三个正确发音。

调整英文格式化输出和英文G2P逻辑

---

api.py

**更新内容如下:**
1. 将语言支持同步到webui版本，即中/日/英/中英/日英/自动
2. 新增文本按标点符号切分功能，支持命令行设置及API传参设置
3. 新增音频返回格式选择，支持wav/ogg/aac，仅支持命令行设置
4. 新增音频流式返回，支持ogg/aac，仅支持命令行设置

Make API Great Again

---

GPT_SoVITS/TTS_infer_pack/TTS.py
GPT_SoVITS/inference_webui.py

拼写修正：
`TTS.py`:
- self.langauges → self.languages
- refer_spepc → ref_spec
- self.precison → self.precision
- self._set_ref_spepc() → self._set_ref_spec()
- lenght → length
- text_segmentaion_method → text_segmentation_method
- tulpe → tuple
- self.configs.langauges → self.configs.languages
- self.prompt_cache["refer_spepc"] → self.prompt_cache["refer_spec"]
- refer_audio_spepc → refer_audio_spec
`inference_webui.py`:
- tts_pipline → tts_pipeline

【Fast Inference 分支】拼写修正

---

tools/uvr5/webui.py

issue #915 
问题定位：
- 转换格式时采用此命令 `"ffmpeg -i %s -vn -acodec pcm_s16le -ac 2 -ar 44100 %s -y" % (inp_path, tmp_path)` 
如果路径存在空格, 会导致命令中断, 无法顺利执行，导致 `TEMP` 下没有相应文件供后续 librosa 读取.
解决方案:
- 将路径用双引号括起.

修复 UVR5 转换命令错误

---

GPT_SoVITS/TTS_infer_pack/TTS.py
GPT_SoVITS/TTS_infer_pack/text_segmentation_method.py
api_v2.py

- 为fast_inference分支适配了全新的WebAPI，不完全兼容之前的api
- 支持wav/ogg/aac/raw音频格式，流式或非流式返回。ogg不支持非流式返回，因为音频过大会导致报错。
- 注意，需要更新LangSegment，否则可能导致LangSegment报错
- 基本可用

[fast_inference] Make API Great Again And Again

---

.gitignore
GPT_SoVITS/TTS_infer_pack/TTS.py

如题，通过简单添加with torch.no_grad()，使3090的速度从73加速到了140
主要是TTS.py里面的这段代码需要with torch.no_grad()
```
pred_semantic_list = [item[-idx:] for item, idx in zip(pred_semantic_list, idx_list)]
upsample_rate = math.prod(self.vits_model.upsample_rates)
audio_frag_idx = [pred_semantic_list[i].shape[0]*2*upsample_rate for i in range(0, len(pred_semantic_list))]
audio_frag_end_idx = [ sum(audio_frag_idx[:i+1]) for i in range(0, len(audio_frag_idx))]
all_pred_semantic = torch.cat(pred_semantic_list).unsqueeze(0).unsqueeze(0).to(self.configs.device)
_batch_phones = torch.cat(batch_phones).unsqueeze(0).to(self.configs.device)
_batch_audio_fragment = (self.vits_model.decode(
all_pred_semantic, _batch_phones, refer_audio_spec
).detach()[0, 0, :])
audio_frag_end_idx.insert(0, 0)
batch_audio_fragment= …
```

【fast_inference_】通过简单添加torch.no_grad()修饰器，可能会使速度加快

---

GPT_SoVITS/text/zh_normalization/num.py
GPT_SoVITS/text/zh_normalization/text_normlization.py

新增以下映射关系
```python
'+': '加', '-': '减', '×': '乘', '÷': '除', '=': '等于
```

添加四则运算的中文格式化处理

---

colab_webui.ipynb

在colab中使用git下载uvr5模型时报错
`fatal: destination path 'uvr5_weights' already exists and is not an empty directory.`
通过在下载前将原本从本仓库下载的uvr5_weights文件夹删除可以解决问题。

在colab中运行colab_webui.ipynb发生的uvr5模型缺失问题

---

tools/asr/fasterwhisper_asr.py
tools/asr/funasr_asr.py

问题描述： #955
问题定位：faster whisper 用 glob 进行文件匹配，路径含特殊字符时未进行转义，导致无法遍历音频文件.
解决方案：换成 FunASR 使用的 `os.listdir`.
其他：

[ASR] 修复FasterWhisper遍历输入路径失败

---

GPT_SoVITS/prepare_datasets/1-get-text.py
webui.py

相关 Issue: #1099
> [!Note]
> ### 过滤掉标注文件中语言不受支持的数据.
> 修改 `prepare_datasets/1-get-text.py`:
> - 获取文本时过滤掉字典 `language_v1_to_language_v2` 不支持的语言类型, 添加 Warning 提示.
>
> ### 优化 WebUI 相应部分的反馈, 
> 修改 `webui.py`:
> - 点击 `开启文本获取` 和 `一键三连` 时, 判断输出结果拼接后的长度是否大于 0, 不大于 0 则表示文本获取失败.
>
修改效果示例: 
> [!Warning]
> - [ ] 建议: 添加全局日志, 方便后续修改?

[优化] 1Aa-文本获取

---

Dockerfile
GPT_SoVITS/TTS_infer_pack/TTS.py
api_v3.py

chore: add the ability of lru cache for api v3 to improve the inference speed when exchange model weights

---

GPT_SoVITS/inference_webui.py

推理只含有标点的直接报错,多个连续标点会被替换,如`',,....'-> '.'`,删除切分后只含有标点的部分

关于标点符号导致参考泄漏的问题

---

GPT_SoVITS/inference_gui.py
GPT_SoVITS/inference_webui.py

以**最小限度**的代码更改实现了该方案，除了在inference_webui.py的末端添加`if __name__ == '__main__':`来防止inference_gui.py在导入函数时触发打开webui界面之外无其它文件改动。
对inference_gui.py的改动如下：
1. 修复缺失的包导入与错误的相对导入问题
2. 解决每次推理都要重新加载模型的问题
3. 允许像webui一样直接输入参考文字与合成文字
4. 参考音频的上传允许选择单个文件
5. 语种添加“中英/日英/多语种混合”并首选“多语种混合”
6. 变量名的规范化以增强可读性
7. 代码精简

解决gui每次推理都要重新加载模型的问题（最终方案）

---

requirements.txt

指定numpy版本1.23.4，与numba==0.56.4匹配报错问题

修正numba与numpy匹配问题，在ubuntu24.04下测试通过

---

GPT_SoVITS/TTS_infer_pack/TTS.py

修复prompt_cache里面没有cache住ref_audio_path，导致每次TTS推理都需要加载一遍reference audio的bug：
- 首次音频帧从速度提升，从3.2s -> 1.7s

fix: 修复prompt_cache里面没有cache住ref_audio_path带来的无效耗时

---

GPT_SoVITS/TTS_infer_pack/TTS.py

在推理完成之后，使用gc控制器对内存进行回收。
@ChasonJiang
#1218

Optimize： 推理完成后自动触发gc回收，避免长时间推理导致内存一直增长。

---

GPT_SoVITS/AR/models/t2s_model.py

y is None at no reference mode, and Nonetype object has no attribute shape

Fix for AttributeError: 'NoneType' object has no attribute 'shape'

---

GPT_SoVITS/s1_train.py

if you have defined your own sampler, you should have to set use_distributed_sampler to False! 当使用自定义的 sampler 时，必须设置 use_distributed_sampler 为 False

Add use_distributed_sampler=False in Trainer

---

GPT_SoVITS/inference_webui.py
GPT_SoVITS/text/chinese.py
GPT_SoVITS/text/english.py
GPT_SoVITS/text/japanese.py
GPT_SoVITS/text/zh_normalization/num.py
GPT_SoVITS/text/zh_normalization/text_normlization.py

**变化：**
1. 调整 https://github.com/RVC-Boss/GPT-SoVITS/pull/1168 中对标点合并的执行位置，应在各语言文本格式化之后而不是之前。
2. 调整纯中文筛选逻辑，允许存在英文字母，英文字母全部按照单个字母发音，以兼容日常口语中夹杂的英文和数学公式。
3. 中文对四则运算符号进行兜底替换，兼容处理“==”，“++”等网络懒人词汇。
4. 中文数学公式运算兼容英文字母、兼容上标⁰¹²³⁴⁵⁶⁷⁸⁹ˣʸⁿ，解决 https://github.com/RVC-Boss/GPT-SoVITS/issues/1349

Better normlization

---

GPT_SoVITS/inference_webui.py
GPT_SoVITS/text/chinese.py
GPT_SoVITS/text/chinese2.py

1、修复训练时候含有中英混合文本会引发报错的问题
2、v2版本chinese同步v1版本新增处理

Fix normalize

---

tools/asr/fasterwhisper_asr.py
tools/asr/funasr_asr.py

> [!CAUTION]
> 修复 Issue #1419 报告的问题，避免选择 Whisper 遇到中文时 FunASR 转写成粤语.
> - [ ] 待定: Whipser 识别粤语时是否需要转 FunASR. 
> [!NOTE]
> - 调整 FunASR 文件的逻辑, 将模型创建单独写成一个函数 `create_model()`;
> - 使用字典 `funasr_models` 避免调用 `only_asr()` 函数时重复创建 `model`;
> - 给 `only_asr()` 函数增加一个语言参数作为入口, 以便 Whisper 后续需要添加粤语选项.
> [!TIP]
> - [x] 在 FunASR 选 zh/yue 测试通过
> - [x] 在 Whipser 选 zh 测试通过

Fix OnlyASR

---

GPT_SoVITS/AR/models/t2s_model.py

- 放弃了在t2s模型中使用@torch.jit.script，确保pytorch环境之间的兼容性。
- 相关issue #1487

[fast_inference] 修复torchscript导致的兼容性问题

---

GPT_SoVITS/text/japanese.py

This pull request introduces a CMUDICT-to-Katakana dictionary, translated using ChatGPT and DeepSeek. This conversion enables the Japanese G2P mode to directly pronounce most common English words in Katakana, improving the compatibility of English terms in Japanese tts applications.
Since the translation was performed by an LLM the accuracy might not be perfect and could benefit from further refinement. However, initial testing indicates that it is currently functional and applicable in most cases.
Additionally, this update restores the "UNK" token's phoneme. During training, this token was learned as a pause, which has shown to be helpful in the Japanese G2P process.

Add LLM translated CMUDICT-KATAKANA dictionary

---

GPT_SoVITS/text/g2pw/g2pw.py

指定字典读取编码，防止用户使用混合编码编辑器操作多音字字典或者英语热词字典后，报GBK编码错误

指定字典读取编码，防止用户使用混合编码编辑器操作多音字字典或者英语热词字典后，报GBK编码错误

---

GPT_SoVITS/text/cantonese.py
requirements.txt

As title, suggest replacing the pyjyutping package with the latest Cantonese G2P package 'ToJyutping' to achieve higher accuracy.
More information: https://github.com/CanCLID/ToJyutping

Replace cantonese g2p with "ToJyutping"

---

GPT_SoVITS/AR/models/t2s_model.py

1、简化sdpa操作后多头维度拼接的逻辑
2、简化batch infer模式下xy_padding_mask的生成：xy_padding_mask不需要channel维度
3、删除process_prompt在batch infer模式下根据padding_mask循环处理batch的冗余逻辑

optimize attention calc logic

---

GPT_SoVITS/AR/models/t2s_model.py

当前推理逻辑返回的semantic code漏掉了推理出的第一个idx，在句子较短的情况下可能出现崩溃

fix inference issue

---

webui.py

CPU 下 batch size 太高没意义，而且在 v3 版本下反而会导致内存占用过多，使系统压缩内存，导致训练速度降低，我这里甚至直接卡在一半了。所以统一降低到系统内存的四分之一

CPU 使用更低 batch size

---

README.md
docs/cn/README.md
docs/ja/README.md
docs/ko/README.md
docs/tr/README.md
tools/uvr5/bs_roformer/attend.py
tools/uvr5/bs_roformer/mel_band_roformer.py
tools/uvr5/bsroformer.py
tools/uvr5/webui.py

UVR分离新增mel_band_roformer模型支持。同时，在保证支持原先代码的情况下，模型额外支持外部配置文件。**需要确保模型名字中包含“roformer”，才能被识别成roformer类的模型。**
支持原先无需配置文件的情况，但是部分新模型使用默认配置文件会因为网络大小不匹配导致无法推理。所以新增外部配置文件。用户可以把配置文件连同模型一起放到`tools/uvr5/uvr5w_weights`文件夹，并且保证配置文件名字和模型名字相同（除后缀外）。例如`roformer_kimmel_unwa_ft.ckpt`和`roformer_kimmel_unwa_ft.yaml`为一对。
运行逻辑：
- 首先判断模型名字中是否含有“roformer”。然后进一步判断是“bs_roformer”还是“mel_band_roformer”。
- 判断是否拥有外置配置文件。如果没有，则采用默认配置文件，并且弹出Warning。

Support for mel_band_roformer

---

install.sh

一键安装脚本中 gcc 版本过高会使 pyopenjtalk 无法正常安装

修复 Linux 无法编译 pyopenjtalk

---

README.md
colab_webui.ipynb
docs/cn/Changelog_CN.md
docs/cn/README.md
docs/ja/Changelog_JA.md
docs/ja/README.md
docs/ko/README.md
docs/tr/README.md
go-webui.bat
go-webui.ps1
install.sh
requirements.txt

1. Updated requirements to support Python 3.11
2. Replace full-width punctuation in docs with half-width
3. Add more tested environments
4. Update Colab notebook
5. Add pretrained model download to install.sh

Support Python 3.11, Clean Docs, and Update Setup

---

config.py

直接运行 `inference_webui.py` 时，`config.py` 文件中会出现错误：
- 环境变量 os.environ["language"] 不存在时，取默认值 "Auto"
- 预定义的 SoVITS_weight_root 和 GPT_weight_root 列表内的元素为文件夹路径，当文件夹路径不存在时进行跳过处理。

Fix mirror errors when running inference webui directly

---

GPT_SoVITS/TTS_infer_pack/TTS.py

* Gracefully handles the case where `self.prompt_cache["refer_spec"][0]` is a **tuple** instead of a `torch.Tensor`.
* Keeps backward compatibility for the original tensor-only path.
```python
raw_entry = self.prompt_cache["refer_spec"][0]
if isinstance(raw_entry, tuple):     # NEW ── unwrap the tuple
raw_entry = raw_entry[0]
refer_audio_spec = raw_entry.to(dtype=self.precision,
device=self.configs.device)
```
```text
File ".../TTS_infer_pack/TTS.py", line 1477, in using_vocoder_synthesis_batched_infer
refer_audio_spec = self.prompt_cache["refer_spec"][0].to(dtype=self.precision, device=self.configs.device)
AttributeError: 'tuple' object has no attribute 'to'
```
`self._get_ref_spec()` currently returns `(spec_tensor, audio_tensor)`.
When that tuple is …

Fix AttributeError: 'tuple' object has no attribute 'to' in using_vocoder_synthesis_batched_infer

---

GPT_SoVITS/text/tone_sandhi.py

当前逻辑会在处理下述有多个"X一X"的pattern时由于索引越界崩溃，如：
[['一起来', 'm'], ['听一听', 'v'], ['唱一唱', 'v'], ['吧', 'y'], [',', 'x']]

fix _merge_yi crash

---

GPT_SoVITS/AR/modules/optim.py
GPT_SoVITS/utils.py
api.py

This small PR resolves the deprecation warnings of the `logger` library:
```python
DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
```
It also fixes a small typos along the way.

Resolve Python Logger warnings

---

GPT_SoVITS/TTS_infer_pack/TTS.py

使用api_v2，用非sovits v2pro模型推理后再切换至v2pro且用同一参考音频会引发下列错误
```
File "E:\Program Files (x86)\GPT-SoVITS\GPT_SoVITS\TTS_infer_pack\TTS.py", line 1233, in run
sv_emb.append(self.sv_model.compute_embedding3(audio_tensor))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "E:\Program Files (x86)\GPT-SoVITS\GPT_SoVITS\sv.py", line 21, in compute_embedding3
if self.is_half==True:wav=wav.half()
^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'half'
```
可能出于性能考虑_get_ref_spec并不会为非v2Pro生成audio张量 。当使用v2Pro模型且第一个audio_tensor为None时重新做缓存

修复if self.is_half==True:wav=wav.half() AttributeError: 'NoneType' object has no attribute 'half'

---

GPT_SoVITS/export_torch_script.py

Avoid dtype inconsistency when exporting.
This is the code I was using 
```
python GPT_SoVITS/c.py \
--gpt_model /home/user1/workspace/bobchenyx/doubao/txdb-e15.ckpt \
--sovits_model /home/user1/workspace/bobchenyx/doubao/txdb_e12_s204.pth \
--ref_audio /home/user1/workspace/bobchenyx/doubao/doubao-ref-ours.wav \
--ref_text /home/user1/workspace/bobchenyx/doubao/doubao-ref.txt \
--output_path /home/user1/workspace/bobchenyx/doubao-export \
--device cpu \
--no-half
```
And I've met this kind of issue.
```
File "/home/user1/workspace/bobchenyx/GPT-SoVITS/GPT_SoVITS/export_torch_script.py", line 1096, in <module>
main()
File "/home/user1/workspace/bobchenyx/GPT-SoVITS/GPT_SoVITS/export_torch_script.py", line 1083, in main
export(
File …
```

Update export_torch_script.py 修复导出过程中精度不匹配

---

GPT_SoVITS/TTS_infer_pack/TTS.py
GPT_SoVITS/configs/tts_infer.yaml

解决 TTS.py 无法真正识别版本 v2Pro、v2ProPlus 的问题。同时更新一版默认配置。

解决 TTS.py 无法真正识别版本 v2Pro、v2ProPlus 的问题

---

GPT_SoVITS/AR/models/t2s_model.py
GPT_SoVITS/configs/tts_infer.yaml

- 现行gpt的loss计算方式没有考虑y[0]的loss (x->y[0])，这可能对gpt的无参考音频模式产生影响。
- 更改x_mask的padding mask为left（不然的话x和y之间有gap），更改loss计算方式（考虑y[0]的情况）
- 直接合并该PR会影响现有预训练权重的微调。最直观的就是top3 acc下降了（毕竟预训练模型没有见过x->y[0]的情况）
- 观察到微调之后，无参考文本模式胡说的概率少了。
- 慎重考虑合并！

修复gpt的loss计算问题
