RVC-Boss/GPT-SoVITS

- README.md
现在别人点prezip就能直接下载，不用进到huggingface tree里再多点两下。稍微改了一下句子以避免歧义+增加可读性
> 更改hugginface链接

- webui.py
Add a function to kill process and its children in Linux platform.
> Kill process in Linux platform

- webui.py
fix https://github.com/RVC-Boss/GPT-SoVITS/issues/11
> fix: users.pth path check

- GPT_SoVITS/inference_webui.py
解决 https://github.com/RVC-Boss/GPT-SoVITS/issues/86 这个issue的问题
> 解决输入目标文本的空行导致报错的问题

- .gitignore
- README.md
- api.py
- config.py
> 重构config相关调用, 自述增添已测试环境

- README.md
- docs/ja/README.md
I created Japanese translated README.
> Add Japanese README

- tools/my_utils.py
- tools/slice_audio.py
- webui.py
> 音频切片部分，提前进行输入路径检查，路径拼接换成 os.path.join

- GPT_SoVITS/inference_webui.py
added i18n for inference webui translations to actually work
> I18n fix for inference webui

- GPT_SoVITS/prepare_datasets/1-get-text.py
- GPT_SoVITS/prepare_datasets/3-get-semantic.py
- api.py
Fixed errors that prevented the program from running, including duplicate API parameter code and incorrect indentation issues. 
@RVC-Boss
> Fix Several Severe Errors

- GPT_SoVITS/inference_webui.py
Fixed the issue in the Bert1 model where multiple-line sentences caused repeated inference in each loop iteration of bert2.
修复了 Bert1 模型中多行句子导致 bert2 每次循环迭代中重复推理的问题。
> Resolved the issue of duplicate inference in the Bert1 model

- GPT_SoVITS/inference_webui.py
> 添加模型记忆功能，不用二次选择模型

- GPT_SoVITS/inference_webui.py
> 引导音频记忆，文本记忆和语种记忆

- GPT_SoVITS/inference_webui.py
Reverts RVC-Boss/GPT-SoVITS#216
> Revert "引导音频记忆，文本记忆和语种记忆"

- README.md
- docs/cn/README.md
- docs/ja/README.md
huggingface按钮引导到的界面是models repo而非huggingface spaces
可能容易造成歧义和误解（）
QWQ
> 【歧义】修改README小细节

- tools/uvr5/vr.py
- tools/uvr5/webui.py
Sometime "is_hp3" doesn't work.
And the output position is incorrect.
> Fix uvr5 hp3 output

- GPT_SoVITS/text/chinese.py
数字转拼音不准的bug，因为将数字一个个分割了调用an2cn当然不准
> fix chinese number to pinyin

- GPT_SoVITS/text/chinese.py
Reverts RVC-Boss/GPT-SoVITS#254
> Revert "fix chinese number to pinyin"

- webui.py
> 修改文件可能不存在的bug

- GPT_SoVITS/inference_webui.py
示例
【1pass】（现在版本）
['我是一名粉刷匠，粉刷本领强，', 'I am a painter with strong painting skills', '，', 'A.B.C.D.A', '_', 'B', '—', 'C', '……', 'D.'] 
['zh', 'en', 'zh', 'en', 'zh', 'en', 'zh', 'en', 'zh', 'en'] 
【2pass】
['我是一名粉刷匠，粉刷本领强，', 'I am a painter with strong painting skills，', 'A.B.C.D.A_', 'B—', 'C……', 'D.'] 
['zh', 'en', 'en', 'en', 'en', 'en']
【result】
['我是一名粉刷匠，粉刷本领强，', 'I am a painter with strong painting skills，A.B.C.D.A_B—C……D.'] 
['zh', 'en']
> 优化日英/中英混合推理分词逻辑

- GPT_SoVITS/inference_webui.py
Reverts RVC-Boss/GPT-SoVITS#374
> Revert "在推理页面添加在线录制参考音频功能用于ZeroShot"

- GPT_SoVITS/AR/models/t2s_model_onnx.py
- GPT_SoVITS/module/attentions_onnx.py
- GPT_SoVITS/module/models_onnx.py
- GPT_SoVITS/onnx_export.py
> Update Onnx Export

- .dockerignore
> 增加.dockerignore文件以便在Docker构建过程中排除不必要的文件夹/文件

- tools/asr/config.py
- tools/asr/fasterwhisper_asr.py
- tools/asr/funasr_asr.py
1、修复在传参时传入model_size+(local)可能引发bash:Syntax error: "(" unexpected.
2、使用fast-whisper时判断为中文则尝试交给funasr处理获取更好的效果
> Adjust-asr

- Dockerfile
- README.md
- config.py
- docker-compose.yaml
- docs/cn/README.md
- docs/ja/README.md
- docs/ko/README.md
1. 更正Dockerfile和文档中原来存在的错误的端口号；进一步优化Dockerfile写法。
2. 由于参数从环境变量中获取，通过eval直接执行会带来不必要的潜在风险，所以改写了is_half的初始化方法为更安全的方式。
> Docker持续优化；环境变量参数获取优化

- colab_webui.ipynb
Reverts RVC-Boss/GPT-SoVITS#510
> Revert "Fix Issue with Share Link Generation in colab_webui.ipynb"

- gpt-sovits_kaggle.ipynb
> 添加Kaggle平台运行脚本

- api.py
首先，感谢作者分享这么好的一个项目。
我是一名程序员，想调用他的api，但是目前只在启动的时候才能指定模型，但是我想在fastApi启动后，【动态修改模型，以此满足同一个api不同的朗读者请求。于是就将推理部分的代码移植到了这里。】
让我们一起为开源努力，yyds
> add set_model，新增了api.py接口中实时更换模型的接口

- README.md
- docs/cn/README.md
- docs/ja/README.md
- docs/ko/README.md
I've optimized the README structure to provide clearer content.
> Optimize the README structure

- GPT_SoVITS/AR/models/t2s_model.py
- GPT_SoVITS/TTS_infer_pack/TTS.py
- GPT_SoVITS/TTS_infer_pack/TextPreprocessor.py
- GPT_SoVITS/inference_webui.py
- GPT_SoVITS/module/models.py
- GPT_SoVITS/prepare_datasets/1-get-text.py
- GPT_SoVITS/prepare_datasets/2-get-hubert-wav32k.py
- GPT_SoVITS/prepare_datasets/3-get-semantic.py
- GPT_SoVITS/s1_train.py
- GPT_SoVITS/s2_train.py
- README.md
- api.py
- docs/cn/README.md
- docs/ja/README.md
- docs/ko/README.md
- webui.py
- [重要] 缓解了batch_size>1时的复读问题，缓解方法是：在T2S模型中，先对phones进行embedding、对bert_features进行project，再pad到相同长度。
- 改进了设置为分段返回时，逐分段地进行Bert特征提取，减少首段的返回延迟。
- 改进了T2S模型中infer_panel_batch_only()方法中，attn_mask的生成方式，以减少padding的影响。
- 增加了分段时间间隔调节，让用户自行选择分段的时间间隔。
- 添加了自定义修改随机数种子，方便复现结果。
> [fast inference] 推理功能增强和改进

- GPT_SoVITS/text/zh_normalization/text_normlization.py
> Fix chinese ellipsis

- GPT_SoVITS/text/zh_normalization/text_normlization.py
> Fix chinese ellipsis for fast_inference_

- GPT_SoVITS/text/english.py
1、修复当中文标点存在英文语句中会被忽略。当结尾是英文是，用来结尾的“。”会被忽略引发复读、吞字。 Fix https://github.com/RVC-Boss/GPT-SoVITS/issues/665
2、匹配“xxx's”所有格，对字典中不存在的所有格进行发音预测。 Fix https://github.com/RVC-Boss/GPT-SoVITS/issues/772
> 修复中文标点在英文中的问题，添加所有格匹配

- GPT_SoVITS/TTS_infer_pack/TTS.py
- GPT_SoVITS/inference_webui.py
在推理按钮下方增加显示本次推理使用的参数，尤其是seed值。
> 在推理按钮下方增加推理使用参数

- GPT_SoVITS/TTS_infer_pack/TTS.py
- GPT_SoVITS/inference_webui.py
- GPT_SoVITS/module/models.py
- 移除了，直接在TTS基类里修改返回值，返回推理参数的部分代码。
- 增加了，当seed=-1时，真实seed的显示逻辑。
- 各位开发者们请注意，小功能不要直接修改TTS基类，而是通过其他手段实现你所增加的小功能。
> [fast_inference] 优化代码结构

- README.md
- docs/cn/README.md
- docs/ja/README.md
- docs/ko/README.md
fix typo s/Licence /License
detail info 
modified:   README.md
modified:   docs/cn/README.md
modified:   docs/ja/README.md
modified:   docs/ko/README.md
> fix typo s/Licence /License

- GPT_SoVITS/AR/models/t2s_model.py
- GPT_SoVITS/TTS_infer_pack/TTS.py
- 改变训练和推理时的mask策略，以修复当batch_size>1时，产生的复读现象。
- 复读的问题是因为mask引起的。
- 我将xy_attn_mask中y[0]的位置设置为了False(True代表mask)详见 [#965 ](https://github.com/RVC-Boss/GPT-SoVITS/issues/965#issuecomment-2051141373)，然后使用三月七数据集（一个很强的bad case）重新训练了两个模型，一个使用了上述方法，一个使用了老方法。发现在下列测试用例中，使用了上述方法的模型没有出现复读情况，使用了老方法的模型出现了复读情况。
- padding策略会影响T2S模型生成的结果，但不是主要原因。
- 要使用fast_inference_分支，需要使用该PR重新微调模型，以减少复读现象。
> [fast_inference] 修复当batch_size>1时，产生的复读现象

- GPT_SoVITS/TTS_infer_pack/TTS.py
- colab_webui.ipynb
- 修复了TTS类中报错，AttributeError: 'list' object has no attribute 'shape'
- 修复了colab_webui.ipynb中，因符号导致的报错
> [fast_inference] 修复了一些bug

- Dockerfile
> 删除重复的 COPY 指令

- GPT_SoVITS/TTS_infer_pack/TTS.py
- 修复报错 TypeError:'type' object is not subscriptable.
> [fast_inference] 修复报错 TypeError:'type' object is not subscriptable.

- api_v2.py
> 允许使用多个进程实例启动

- GPT_SoVITS/module/models.py
https://github.com/RVC-Boss/GPT-SoVITS/issues/747#issuecomment-2115138707
> nullcontext少了对括号

- GPT_SoVITS/inference_cli.py
- GPT_SoVITS/inference_webui.py
命令行推理工具， 使用示例：
python GPT_SoVITS/inference_cli.py --gpt_model GPT_weights/fan-e15.ckpt --sovits_model SoVITS_weights/fan_e15_s135.pth --ref_audio /data/voice/chinese_poem2.wav --ref_text /data/voice/ref.txt --target_language "多语种混合"  --ref_language 中文 --target_text /data/voice/input.txt --output_path output/
> inference cli tool

- tools/cmd-denoise.py
> 修复了DS_STORE带来的问题

- GPT_SoVITS/inference_webui.py
> fix: 解决按标点符号切分时小数会被切分(#1084)

- tools/my_utils.py
- tools/uvr5/webui.py
- webui.py
> Clean Path

- docs/en/Changelog_EN.md
> [!NOTE]
> 上传英文版本的更新日志. (Upload the English version of the Change Log.)
>
> 由 GPT-4o 初步翻译，然后结合 DeepSeek 和人工进行二次格式化和校对. 
> (Initially translated by GPT-4o, then reformatted and proofread in conjunction with DeepSeek and human review.)
> Upload Changelog EN

- tools/uvr5/bs_roformer/attend.py
- tools/uvr5/bs_roformer/bs_roformer.py
- tools/uvr5/bsroformer.py
- tools/uvr5/webui.py
需下载模型后使用：
下载 [BS Roformer (viperx edition) ](https://github.com/TRvlvr/model_repo/releases/download/all_public_uvr_models/model_bs_roformer_ep_317_sdr_12.9755.ckpt)到tools/uvr5/uvr5_weights，保存为Bs_Roformer.pth
> 为UVR5模块添加Bs_Roformer模型

- requirements.txt
- tools/uvr5/bs_roformer/bs_roformer.py
- tools/uvr5/bsroformer.py
**修改：**
1. 去除非必要的依赖
2. 修改num_overlap
> Simplify bs_roformer

- GPT_SoVITS/inference_webui.py
- GPT_SoVITS/text/cantonese.py
> Add Lang Support

- GPT_SoVITS/feature_extractor/cnhubert.py
- GPT_SoVITS/text/cleaner.py
> Repair detail

- GPT_SoVITS/inference_webui.py
- GPT_SoVITS/text/cleaner.py
- api.py
1. 优化短句padding逻辑，防止长句短音漏padding的情况。https://github.com/RVC-Boss/GPT-SoVITS/issues/1403
2. 鉴于新模型英文提升，减少短词padding，优化连贯性。
> Optimize short sentence

- GPT_SoVITS/text/english.py
> Fix hyphen

- .gitignore
- GPT_SoVITS/AR/models/t2s_model.py
- GPT_SoVITS/TTS_infer_pack/TTS.py
- 优化了t2s在batch inference的mask策略，使音频合成的质量更加稳定；
> [fast_inference] 优化batch inference的mask策略

- GPT_SoVITS/AR/models/t2s_model.py
> [fast_inference]  兼容torch.jit.script

- GPT_SoVITS/text/tone_sandhi.py
> Merge_yi修复

- .gitignore
- GPT_SoVITS/AR/models/t2s_model.py
- GPT_SoVITS/AR/models/utils.py
- GPT_SoVITS/TTS_infer_pack/TTS.py
- GPT_SoVITS/TTS_infer_pack/TextPreprocessor.py
- GPT_SoVITS/TTS_infer_pack/__init__.py
- GPT_SoVITS/TTS_infer_pack/text_segmentation_method.py
- GPT_SoVITS/configs/tts_infer.yaml
- GPT_SoVITS/feature_extractor/cnhubert.py
- GPT_SoVITS/inference_webui_fast.py
- api_v2.py
- webui.py
- 修改了部分t2s模型的推理代码，使之兼容batched inference，原则上不影响原来的推理效果。
- 合并且升级了原fast_inference_分支，使之兼容v2的模型。
- 修改了TextPreprocessor类中的前端处理代码，使其与main分支尽量保持一致。
- 移除了原fast_inference_分支的api_v3.py
- 在webui.py推理界面增加了“启用并行推理版本”选项，方便用户自行选择。
> All in one!  合并main分支和fast_inference_分支

- GPT_SoVITS/TTS_infer_pack/TTS.py
- api_v2.py
> 修改api_v2文档

- GPT_SoVITS/TTS_infer_pack/TTS.py
- api_v2.py
> 优化tts_config代码逻辑

- GPT_SoVITS/module/models_onnx.py
- GPT_SoVITS/onnx_export.py
我试着改了一下 onnx_export.py 让它可以导出 v2 的版本。我自己在开启了 Debug 的情况下确实是生成了语音。但是效果不是很好。
我不是搞 python 和 ml 的，不是很熟悉这块。希望大佬可以帮忙 review 一下
> Fix onnx_export to support v2

- GPT_SoVITS/text/chinese2.py
即通过 os.environ.get 从 bert_path 环境变量里去获取正确的路径值。
> 修复 Chinese2.py 中 model_source 的路径获取

- GPT_SoVITS/text/japanese.py
Reverts RVC-Boss/GPT-SoVITS#1660
> Revert "Add LLM translated CMUDICT-KATAKANA dictionary"

- GPT_SoVITS/text/japanese.py
Fix bug in #1660, and add try-catch on userdict. Userdict import may failed in some situations.
> Fix bug in  #1660 and #1667

- GPT_SoVITS/export_torch_script.py
* 优化了导出的 bert. (依照 transform 的 导出成 torch-script 文档。使用了 `torchscript=True` 来加载 Bert，但是没有测试是否结果有显著提升)
* 导出时使用 `torch._dynamo.mark_dynamic` 标记动态维度
* 添加命令选项 --export_common_model 用来在导出时额外导出 ssl 和 bert。因为它们是可以公用的模型。
* 添加命令选项 --device 可以选择在 cpu 或 cuda 上导出。（在 cuda 上导出时，对于我本机是会快很多，但是导出的模型不可以在 cpu 上使用。但是 cpu 导出的模型就可以在 cuda 上使用。）
> 优化 export_torch_script.py

- GPT_SoVITS/text/g2pw/g2pw.py
> Fix g2pw bug

- docs/ja/README.md
> Improve Japanese translation

- GPT_SoVITS/configs/s2.json
- GPT_SoVITS/f5_tts/model/backbones/dit.py
- GPT_SoVITS/module/models.py
- GPT_SoVITS/s2_train_v3.py
- webui.py
单卡 BS1 使用grad ckpt
单卡 BS1 不使用grad ckpt
> update Gradient Checkpointing to reduce VRAM usage

- GPT_SoVITS/inference_webui.py
- GPT_SoVITS/text/LangSegmenter/__init__.py
- GPT_SoVITS/text/LangSegmenter/langsegmenter.py
- GPT_SoVITS/text/english.py
- README.md
- requirements.txt
1. 引入[split-lang](https://github.com/DoodleBears/split-lang)作为语言分割工具，提升中日韩语切分能力
2. 在英文格式化重新实现原语言切分工具对大写英文的预处理功能
> 切换新的语言分割工具

- GPT_SoVITS/TTS_infer_pack/TextPreprocessor.py
- GPT_SoVITS/TTS_infer_pack/text_segmentation_method.py
- GPT_SoVITS/inference_webui.py
- GPT_SoVITS/text/en_normalization/expend.py
- GPT_SoVITS/text/english.py
1. 引入新的英文格式化规则 by @Cosmo-klara
2. 为并行推理文字处理部分同步更新LangSegmenter
> Add en_normalization and fix LangSegmenter

- webui.py
1. 对专用+共享显存大于14G的开启default_batch_size=1。
2. 对专用+共享显存大于12G小于14G的开启default_batch_size=1，并强制梯度检查。
_*536.40以上驱动版本支持共享显存特性。_
> 允许使用共享显存开启V3训练

- GPT_SoVITS/text/LangSegmenter/langsegmenter.py
- GPT_SoVITS/text/korean.py
> Fix invalid path

- GPT_SoVITS/inference_webui.py
- GPT_SoVITS/text/LangSegmenter/langsegmenter.py
CJK短字符无法使用模型判断时，利用规则判断。
Fix https://github.com/RVC-Boss/GPT-SoVITS/issues/2116
> Fix Short CJK LangSegmenter

- GPT_SoVITS/text/LangSegmenter/langsegmenter.py
- GPT_SoVITS/text/japanese.py
- GPT_SoVITS/text/korean.py
- requirements.txt
1. 匹配fast_langdetect更新
2. 补上目录里少允许的“-”
fix https://github.com/RVC-Boss/GPT-SoVITS/issues/2139
fix https://github.com/RVC-Boss/GPT-SoVITS/issues/2137
> 匹配 fast_langdetect 更新

- GPT_SoVITS/module/models.py
- GPT_SoVITS/text/chinese.py
- GPT_SoVITS/text/chinese2.py
- api.py
1. v3/v3lora模型API适配
2. 新增采样步数sample_steps、超分选项if_sr
3. 去除多余的输出
fix https://github.com/RVC-Boss/GPT-SoVITS/issues/2133 https://github.com/RVC-Boss/GPT-SoVITS/issues/2066 https://github.com/RVC-Boss/GPT-SoVITS/issues/2121 https://github.com/RVC-Boss/GPT-SoVITS/issues/2060 https://github.com/RVC-Boss/GPT-SoVITS/issues/2051 https://github.com/RVC-Boss/GPT-SoVITS/issues/2052 https://github.com/RVC-Boss/GPT-SoVITS/issues/2035
> V3模型的API适配

- GPT_SoVITS/AR/models/t2s_model.py
- GPT_SoVITS/TTS_infer_pack/TTS.py
- GPT_SoVITS/configs/tts_infer.yaml
> 修复gpt的padding mask的问题

- .gitignore
- GPT_SoVITS/BigVGAN/alias_free_activation/torch/act.py
- GPT_SoVITS/BigVGAN/alias_free_activation/torch/resample.py
- GPT_SoVITS/BigVGAN/bigvgan.py
- GPT_SoVITS/BigVGAN/meldataset.py
- GPT_SoVITS/BigVGAN/utils0.py
- GPT_SoVITS/TTS_infer_pack/TTS.py
- GPT_SoVITS/TTS_infer_pack/TextPreprocessor.py
- GPT_SoVITS/configs/tts_infer.yaml
- GPT_SoVITS/inference_webui_fast.py
- api_v2.py
- tools/audio_sr.py
为api_v2和inference_webui_fast适配V3版本
> 为api_v2和inference_webui_fast适配V3版本

- GPT_SoVITS/text/g2pw/onnx_api.py
- README.md
- docs/cn/README.md
- docs/ja/README.md
- docs/ko/README.md
- docs/tr/README.md
Fix https://github.com/RVC-Boss/GPT-SoVITS/issues/2215
> 更新G2PWModel下载链接

- GPT_SoVITS/export_torch_script.py
- GPT_SoVITS/export_torch_script_v3.py
- GPT_SoVITS/f5_tts/model/backbones/dit.py
- GPT_SoVITS/module/models_onnx.py
> feat: 添加导出 v3 的 script

- .gitignore
- GPT_SoVITS_Inference.ipynb
- README.md
- colab_webui.ipynb
- constraints.txt
- docs/cn/README.md
- docs/ja/README.md
- docs/ko/README.md
- docs/tr/README.md
- extra-req.txt
- gpt-sovits_kaggle.ipynb
- install.sh
- requirements.txt
**Solution References:**  
- [pyopenjtalk#99](https://github.com/r9y9/pyopenjtalk/issues/99)  
- [open_jtalk#10](https://github.com/r9y9/open_jtalk/pull/10)
**Related Issues:**  
- [#2233](https://github.com/RVC-Boss/GPT-SoVITS/issues/2233)  
- [#2231](https://github.com/RVC-Boss/GPT-SoVITS/issues/2231)
- [#1131](https://github.com/RVC-Boss/GPT-SoVITS/issues/1131)
---
**Related Issues:**  
- [#1841](https://github.com/RVC-Boss/GPT-SoVITS/issues/1841)  
- [#1819](https://github.com/RVC-Boss/GPT-SoVITS/issues/1819)  
- [#1192](https://github.com/RVC-Boss/GPT-SoVITS/issues/1192)
- [#671](https://github.com/RVC-Boss/GPT-SoVITS/issues/671)  
- [#492](https://github.com/RVC-Boss/GPT-SoVITS/issues/492)
---
**Solution Reference:**  
- [gradio#10792](https://github.com/gradio-app/gradio/issues/1079 …
> Fix dependency-related issues via requirements update

- GPT_SoVITS/TTS_infer_pack/TTS.py
> 为sovits_v3 适配并行推理

- requirements.txt
https://github.com/RVC-Boss/GPT-SoVITS/pull/403
https://github.com/RVC-Boss/GPT-SoVITS/issues/2308
> Update librosa version

- GPT_SoVITS/export_torch_script_v3.py
- GPT_SoVITS/export_torch_script_v3v4.py
- GPT_SoVITS/module/models_onnx.py
我感觉效果和python本身有差距，但是能跑就是了，先用着后面再优化吧
> 添加导出 v4 的部分

- .pre-commit-config.yaml
- config.py
- webui.py
Modified gradio Layout
Refactor WebUI half-precision and GPU detection logic
> Make Auto-Detection Great Again

- GPT_SoVITS/inference_webui.py
- GPT_SoVITS/inference_webui_fast.py
- GPT_SoVITS/process_ckpt.py
> fix configs error

- GPT_SoVITS/TTS_infer_pack/TextPreprocessor.py
- GPT_SoVITS/inference_webui.py
- api.py
1. Update api.py
2. Fix https://github.com/RVC-Boss/GPT-SoVITS/issues/2445
> support v4 v2Pro v2ProPlus for api & optimize LangSegmenter

- api_v2.py
There are some syntax errors in api_v2.py
> Fixed syntax errors for api_v2.py

- GPT_SoVITS/text/g2pw/onnx_api.py
> 确保ort provider可用

- tools/assets.py
> fix: 修正 WebUI 中的错误链接
